### ISSUE TITLE
Investigate rails-ujs

### ISSUE THREAD

**Issue by imranismail** [imranismail/turbolinks.ex#3]
Investigate [rails-ujs](https://github.com/rails/rails-ujs) and how it can be used

**Comment by imranismail** [comment]
Rails ujs has been merged to Rails 5 ActionView making it difficult to use via NPM. Unless they change that I wont be updating the guide.

**Comment by abitdodgy** [comment]
@imranismail just an FYI, there's a [phoenix_ujs](https://github.com/jalkoby/phoenix_ujs) package that doesn't depend on jQuery.

**Comment by imranismail** [comment]
Looks like tenderlove just updated the NPM package. I tested and it works fine. Will be updating the README.md

Reduced my bundle size by a whole lot 👍

**Comment by markschultz** [comment]
any update on this? i've been messing around with both jquery-ujs and phoenix_ujs and I haven't been able to get the latter one to work yet.

**Comment by imranismail** [comment]
I can try it out tomorrow and let you know my findings.

**Comment by sn3p** [comment]
Status on this? `jquery-ujs` and `phoenix_html` are in conflict (see #6).
[phoenix_ujs](https://github.com/jalkoby/phoenix_ujs) looks like a nice alternative!

**Comment by markschultz** [comment]
here [(gist)](https://gist.github.com/markschultz/8a723a094ce8238863472811cea96a43) is my mostly working phoenix_ujs example. I noticed that the xhr? function was always returning false due to the case of "XMLHttpRequest". The app.js is to handle the redirects. If there was a form submit followed by a 302 then turbolinks.ex will send JS that we execute. Otherwise we use turbolinks js library to 'visit' the returned html.

**Comment by imranismail** [comment]
@markschultz would downcasing and comparing it work?

```elixir
def xhr?(conn) do
  conn
  |> Plug.Conn.get_req_header("x-requested-with")
  |> Enum.any?(&(String.downcase(&1) == "xmlhttprequest"))
end
```

**Comment by markschultz** [comment]
yes, it would. I've also opened https://github.com/jalkoby/phoenix_ujs/issues/11 as i believe that's the correct place for a fix.

**Comment by imranismail** [comment]
I'll leave this PR open. The most stable one is by far jquery-ujs. I've had some issues with rails-ujs a few months ago which is why I held back on updating the README with it.

Moving forward I would like to recommend dropping jquery-ujs and use a minimal one that has no dependency on jquery.

Either `phoenix_ujs` or `rails_ujs` would fit this.

https://github.com/jalkoby/phoenix_ujs
https://www.npmjs.com/package/rails-ujs
