### ISSUE TITLE
Jquery and jquery-ujs conflict

### ISSUE THREAD

**Issue by dokuzbir** [imranismail/turbolinks.ex#6]
Jquery and jquery-ujs and conflict and my  all method:delete links giving no route error. After changing jQuery: 'jquery' to jquery: 'jquery'  links work. But turbolinks doesnt work after that. I created a new app from zero with readme i still get same error

app.js

> import "phoenix_html"
> import "jquery-ujs"

Brunch-config.js

> npm: {
> enabled: true,
> globals: {
> $: 'jquery',
> jQuery: 'jquery' }};

**Comment by sn3p** [comment]
+1 same problem here!

Renaming `jQuery: "jquery"` to `jquery: "jquery"` will break `jquery-ujs`. That's why the links work again. Similar effect when you remove `import "jquery-ujs";` but then Turbolinks won't work properly.

**Comment by dokuzbir** [comment]
I got same error with rails-ujs too. Only phoenix_ujs works

**Comment by sn3p** [comment]
I've created an [issue](https://github.com/phoenixframework/phoenix_html/issues/192) similar to this problem on [phoenix_html](https://github.com/phoenixframework/phoenix_html).

Also tried creating a **[simple test case/app](https://github.com/sn3p/phoenix_turbolinks_testcase)** to explain and reproduces the problem.

**Comment by imranismail** [comment]
It's not jquery that is conflicting. It's phoenix_html and jquery_ujs that is conflicting.

In app.js

```diff
-- import "phoenix_html"
++ import "jquery-ujs"
```

for example with phoenix html if you use this

`<%= link "Logout", to: session_path(@conn, :delete), method: :delete %>`

generates this html output

`<a href="/session" data-csrf="csrf_token" data-method="delete" data-to="/session">Logout</a>`

With jquery-ujs you want this instead.

`<%= link "Logout", to: session_path(@conn, :delete), data: [remote: true, method: :delete] %>`

generates this html output

`<a href="/session" data-remote="true" data-method="delete">Logout</a>`

**Comment by sn3p** [comment]
@imranismail thanks, that seems to work. Maybe add this info to the README?

**Comment by sn3p** [comment]
@imranismail one more question. Would something similar be possible using [`button/2`](https://hexdocs.pm/phoenix_html/Phoenix.HTML.Link.html#button/2)?

I tried:

```ex
button("Logout", to: session_path(@conn, :delete), data: [method: :delete, remote: true])
```

Output:

```html
<button data-csrf="csrf_token" data-method="delete" data-remote="true" data-to="/session">Logout</button>
```

On click I get this error:

```
DELETE http://localhost:4000/ 404 (Not Found)
```

The button has no `href` and it doesn't follow the `data-to` value.
