### ISSUE TITLE
change the order of the turbolink plug

### ISSUE THREAD

**Issue by happysalada** [imranismail/turbolinks.ex#8]
according to this blog post, the turbolinks plug shoudl be placed before fetch_flash
https://elixirforum.com/t/turbolinks-with-phoenix/1091/40 (last post on the link)
I am about to install the library and make the test.
If you feel this issue is irrelevant, feel free to close it.

**Comment by imranismail** [comment]
@happysalada Have you tried out the proposed change?

**Comment by happysalada** [comment]
It seemed to work. I have personally paused using turbolinks for a bit until I managed to refactor all the javascript state I had out of the page directly. I will be able to tell you in more details in a month probably
